name: Android Emulator Cloudflare
on:
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      
      - name: Install Cloudflared
        run: |
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb
      
      - name: Run Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          profile: Nexus 6
          cores: 2
          ram-size: 4096M
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio
          script: |
            adb wait-for-device
            adb root
            sleep 3
            adb tcpip 5555
            sleep 3
            cloudflared tunnel --url tcp://localhost:5555 > cf.log 2>&1 &
            sleep 15
            grep -oP 'https://.*?.trycloudflare.com' cf.log
            echo "Use: scrcpy --tcpip=HOST:443"
            sleep 21000
