name: Rooted Android 11 AVD - Max Performance + Play Store + KCP

on:
  workflow_dispatch:
    inputs:
      duration:
        description: 'Session duration in hours (max 6)'
        required: false
        default: '6'

jobs:
  run-emulator:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Maximize Build Space
        run: |
          echo "🗑️ Freeing up disk space..."
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/share/swift
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/share/kotlinc
          sudo rm -rf /usr/local/lib/node_modules
          sudo docker image prune --all --force
          sudo apt-get clean
          df -h

      - name: Enable KVM Hardware Acceleration
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install FRP Client v0.58.1
        run: |
          wget -q https://github.com/fatedier/frp/releases/download/v0.58.1/frp_0.58.1_linux_amd64.tar.gz
          tar -xzf frp_0.58.1_linux_amd64.tar.gz
          sudo cp frp_0.58.1_linux_amd64/frpc /usr/local/bin/
          sudo chmod +x /usr/local/bin/frpc
          rm -rf frp_0.58.1_linux_amd64*

      - name: Create FRP Client Configuration with KCP
        run: |
          cat > frpc.toml << 'EOF'
          serverAddr = "159.195.6.61"
          serverPort = 7000
          transport.protocol = "kcp"
          
          [[proxies]]
          name = "github-avd-adb"
          type = "tcp"
          localIP = "127.0.0.1"
          localPort = 5555
          remotePort = 5555
          
          [[proxies]]
          name = "github-avd-console"
          type = "tcp"
          localIP = "127.0.0.1"
          localPort = 5554
          remotePort = 5554
          EOF

      - name: Download rootAVD for Root Access
        run: |
          echo "📥 Downloading rootAVD..."
          wget -q https://github.com/newbit1/rootAVD/archive/refs/heads/master.zip -O rootAVD.zip
          unzip -q rootAVD.zip
          chmod +x rootAVD-master/rootAVD.sh
          echo "✅ rootAVD downloaded"

      - name: AVD Cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-30-rooted-pixel6pro-playstore-maxperf-v1

      - name: Create and Root AVD Snapshot
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis_playstore
          arch: x86_64
          profile: pixel_6_pro
          ram-size: 6144M
          heap-size: 1024M
          disk-size: 12288M
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -camera-front none
          disable-animations: true
          script: |
            echo "✅ AVD created - Android 11 with Play Store"
            adb root
            adb wait-for-device
            echo "🔓 AVD has root access enabled"

      - name: Apply Magisk Root
        if: steps.avd-cache.outputs.cache-hit != 'true'
        run: |
          echo "🔧 Applying Magisk root..."
          cd rootAVD-master
          ./rootAVD.sh ~/.android/avd/*/system-images/android-30/google_apis_playstore/x86_64/ramdisk.img
          echo "✅ Magisk applied - Root access granted"

      - name: Start FRP KCP Tunnel
        run: |
          echo "🚀 Starting FRP with KCP protocol..."
          nohup frpc -c frpc.toml > frpc.log 2>&1 &
          sleep 5
          if pgrep -x "frpc" > /dev/null; then
            echo "✅ FRP KCP tunnel started"
          else
            echo "❌ FRP failed to start"
            cat frpc.log
            exit 1
          fi

      - name: Create Monitoring Script
        run: |
          cat > monitor.sh << 'SCRIPT'
          #!/bin/bash
          DURATION_HOURS=$1
          DURATION_SECONDS=$((3600 * DURATION_HOURS))
          START_TIME=$(date +%s)
          
          echo "⏱️  Session: ${DURATION_HOURS} hours"
          echo "🕐 Started: $(date)"
          echo "🔥 Protocol: KCP (Low Latency)"
          echo "🔓 Root: Enabled (Magisk)"
          echo "🏪 Play Store: Enabled"
          echo "💾 RAM: 6GB | Storage: 12GB"
          echo "🤖 Android 11 (API 30)"
          echo "✅ Maximum Performance + Root"
          echo ""
          
          ITERATION=0
          while true; do
            CURRENT_TIME=$(date +%s)
            ELAPSED=$((CURRENT_TIME - START_TIME))
            
            if [ $ELAPSED -ge $DURATION_SECONDS ]; then
              echo ""
              echo "✅ Session completed after ${DURATION_HOURS} hours"
              break
            fi
            
            REMAINING=$((DURATION_SECONDS - ELAPSED))
            HOURS=$((REMAINING / 3600))
            MINUTES=$(((REMAINING % 3600) / 60))
            
            ITERATION=$((ITERATION + 1))
            if [ $((ITERATION % 60)) -eq 0 ]; then
              DEVICES=$(adb devices | grep -c "5555.*device" || echo "0")
              FRP_STATUS="✅"
              pgrep -x "frpc" > /dev/null || FRP_STATUS="❌"
              echo "[$(date '+%H:%M:%S')] ⏳ ${HOURS}h ${MINUTES}m | 📱 ADB: ${DEVICES} | 🔗 KCP: ${FRP_STATUS}"
            fi
            
            sleep 1
          done
          
          echo "Session ended: $(date)"
          SCRIPT
          chmod +x monitor.sh

      - name: Start Rooted Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis_playstore
          arch: x86_64
          profile: pixel_6_pro
          ram-size: 6144M
          heap-size: 1024M
          disk-size: 12288M
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -camera-front none -memory 6144 -cores 4 -skin 1080x2400 -writable-system
          disable-animations: true
          script: |
            echo "========================================="
            echo "   🚀 ROOTED Android 11 Emulator"
            echo "   💪 MAXIMUM PERFORMANCE MODE"
            echo "========================================="
            echo ""
            
            # Enable root access
            adb root
            adb wait-for-device
            adb remount
            
            echo "🔓 Verifying root access..."
            adb shell "su -c 'id'" || echo "Installing Magisk..."
            
            adb devices -l
            echo ""
            echo "⚙️  Enabling ADB over TCP/IP..."
            adb tcpip 5555
            sleep 5
            adb connect 127.0.0.1:5555
            sleep 2
            echo ""
            echo "========================================="
            echo "   📱 Device Information"
            echo "========================================="
            echo "Android Version: 11"
            echo "API Level: 30"
            echo "CPU: x86_64"
            echo "Model: Pixel 6 Pro"
            echo "RAM: 6GB"
            echo "Storage: 12GB"
            echo "Root Access: ✅ Enabled (Magisk)"
            echo "Play Store: ✅ Installed"
            echo ""
            
            # Check root status
            echo "🔐 Root Status:"
            adb shell "su -c 'whoami'" && echo "✅ Root access confirmed" || echo "⚠️ Root pending (grant on first use)"
            
            echo ""
            echo "💾 Storage Status:"
            adb -s 127.0.0.1:5555 shell df -h /data | grep -v Filesystem
            echo ""
            echo "🧠 Memory Status:"
            adb -s 127.0.0.1:5555 shell cat /proc/meminfo | grep MemTotal
            echo ""
            echo "========================================="
            echo "   🌐 KCP TUNNEL READY (LOW LATENCY)"
            echo "========================================="
            echo ""
            echo "Connect from YOUR device:"
            echo ""
            echo "  📱 Bugjaeger: 159.195.6.61:5555"
            echo "  💻 ADB: adb connect 159.195.6.61:5555"
            echo "  🔓 Root: su (Magisk installed)"
            echo "  🏪 Play Store: Available"
            echo ""
            echo "========================================="
            echo "VPS IP: 159.195.6.61"
            echo "ADB Port: 5555"
            echo "Protocol: KCP (UDP) - Low Latency"
            echo "Android: 11 (API 30)"
            echo "RAM: 6GB | Storage: 12GB"
            echo "Root: ✅ Magisk Enabled"
            echo "Play Store: ✅ Enabled"
            echo "Performance: 🚀 MAXIMUM"
            echo "========================================="
            echo ""
            ./monitor.sh ${{ github.event.inputs.duration }}

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rooted-avd-logs-${{ github.run_number }}
          path: |
            frpc.log
            frpc.toml
          retention-days: 7
