name: Rooted Android 11 + Manual Play Store - Max Performance + KCP

on:
  workflow_dispatch:
    inputs:
      duration:
        description: 'Session duration in hours (max 6)'
        required: false
        default: '6'

jobs:
  run-emulator:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Enable KVM Hardware Acceleration
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Free Up Disk Space
        run: |
          echo "🗑️ Freeing up disk space..."
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo rm -rf /usr/local/share/boost
          sudo docker image prune --all --force
          sudo apt-get clean

      - name: Install FRP Client v0.58.1
        run: |
          wget -q https://github.com/fatedier/frp/releases/download/v0.58.1/frp_0.58.1_linux_amd64.tar.gz
          tar -xzf frp_0.58.1_linux_amd64.tar.gz
          sudo cp frp_0.58.1_linux_amd64/frpc /usr/local/bin/
          sudo chmod +x /usr/local/bin/frpc
          rm -rf frp_0.58.1_linux_amd64*

      - name: Create FRP Client Configuration with KCP
        run: |
          cat > frpc.toml << 'EOF'
          serverAddr = "159.195.6.61"
          serverPort = 7000
          transport.protocol = "kcp"
          
          [[proxies]]
          name = "github-avd-adb"
          type = "tcp"
          localIP = "127.0.0.1"
          localPort = 5555
          remotePort = 5555
          
          [[proxies]]
          name = "github-avd-console"
          type = "tcp"
          localIP = "127.0.0.1"
          localPort = 5554
          remotePort = 5554
          EOF

      - name: Download Play Store APKs
        run: |
          echo "📥 Downloading Play Store components..."
          mkdir -p playstore-apks
          cd playstore-apks
          
          # Download Play Store and Services (OpenGApps links)
          wget -q https://github.com/opengapps/arm64/releases/download/20240715/open_gapps-arm64-11.0-pico-20240715.zip -O gapps.zip
          unzip -q gapps.zip
          echo "✅ Play Store APKs downloaded"

      - name: AVD Cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-30-rooted-playstore-manual-v1

      - name: Create Rooted AVD Snapshot
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel_6_pro
          ram-size: 6144M
          heap-size: 1024M
          disk-size: 12288M
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -camera-front none -writable-system
          disable-animations: true
          script: |
            echo "✅ Rooted AVD created - installing Play Store..."
            adb root
            adb wait-for-device
            adb remount
            
            # Install Play Services Framework
            adb push playstore-apks/Core/com.google.android.gms-*.apk /system/priv-app/
            
            # Install Play Store
            adb push playstore-apks/Core/com.android.vending-*.apk /system/priv-app/
            
            # Set permissions
            adb shell "chmod 644 /system/priv-app/*.apk"
            
            echo "✅ Play Store installed on rooted AVD"

      - name: Start FRP KCP Tunnel
        run: |
          echo "🚀 Starting FRP with KCP protocol..."
          nohup frpc -c frpc.toml > frpc.log 2>&1 &
          sleep 5
          if pgrep -x "frpc" > /dev/null; then
            echo "✅ FRP KCP tunnel started"
          fi

      - name: Create Monitoring Script
        run: |
          cat > monitor.sh << 'SCRIPT'
          #!/bin/bash
          DURATION_HOURS=$1
          DURATION_SECONDS=$((3600 * DURATION_HOURS))
          START_TIME=$(date +%s)
          
          echo "⏱️  Session: ${DURATION_HOURS} hours"
          echo "🕐 Started: $(date)"
          echo "🔥 Protocol: KCP (Low Latency)"
          echo "🔓 Root: ✅ Enabled"
          echo "🏪 Play Store: ✅ Manual Install"
          echo "💾 RAM: 6GB | Storage: 12GB"
          echo "🤖 Android 11 (API 30)"
          echo ""
          
          ITERATION=0
          while true; do
            CURRENT_TIME=$(date +%s)
            ELAPSED=$((CURRENT_TIME - START_TIME))
            
            if [ $ELAPSED -ge $DURATION_SECONDS ]; then
              echo "✅ Session completed"
              break
            fi
            
            REMAINING=$((DURATION_SECONDS - ELAPSED))
            HOURS=$((REMAINING / 3600))
            MINUTES=$(((REMAINING % 3600) / 60))
            
            ITERATION=$((ITERATION + 1))
            if [ $((ITERATION % 60)) -eq 0 ]; then
              DEVICES=$(adb devices | grep -c "5555.*device" || echo "0")
              FRP_STATUS="✅"
              pgrep -x "frpc" > /dev/null || FRP_STATUS="❌"
              echo "[$(date '+%H:%M:%S')] ⏳ ${HOURS}h ${MINUTES}m | 📱 ADB: ${DEVICES} | 🔗 KCP: ${FRP_STATUS}"
            fi
            
            sleep 1
          done
          SCRIPT
          chmod +x monitor.sh

      - name: Start Rooted Emulator with Play Store
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel_6_pro
          ram-size: 6144M
          heap-size: 1024M
          disk-size: 12288M
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -camera-front none -memory 6144 -cores 4 -skin 1080x2400 -writable-system
          disable-animations: true
          script: |
            echo "========================================="
            echo "   🚀 Rooted Android 11 + Play Store"
            echo "   💪 MAXIMUM PERFORMANCE"
            echo "========================================="
            echo ""
            
            # Enable root
            adb root
            adb wait-for-device
            adb remount
            
            # Enable TCP/IP
            adb tcpip 5555
            sleep 5
            adb connect 127.0.0.1:5555
            sleep 2
            
            echo "========================================="
            echo "   📱 Device Information"
            echo "========================================="
            echo "Android Version: 11"
            echo "API Level: 30"
            echo "RAM: 6GB | Storage: 12GB"
            echo "Root: ✅ Enabled (adb root)"
            echo "Play Store: ✅ Manually Installed"
            echo ""
            
            # Verify root
            echo "🔐 Root Status:"
            adb shell "su -c 'whoami'" && echo "✅ Root verified" || echo "Root via adb root"
            
            # Check Play Store installation
            echo ""
            echo "🏪 Play Store Status:"
            adb shell "pm list packages | grep vending" && echo "✅ Play Store detected" || echo "⚠️ Play Store may need activation"
            
            echo ""
            echo "========================================="
            echo "   🌐 KCP TUNNEL READY"
            echo "========================================="
            echo ""
            echo "Connect: 159.195.6.61:5555"
            echo "Protocol: KCP (Low Latency)"
            echo "Root: adb root (already enabled)"
            echo "Play Store: Open Settings → Accounts"
            echo ""
            echo "========================================="
            echo "VPS IP: 159.195.6.61"
            echo "ADB Port: 5555"
            echo "Protocol: KCP (UDP)"
            echo "Android: 11 | RAM: 6GB | Storage: 12GB"
            echo "Root: ✅ | Play Store: ✅"
            echo "========================================="
            echo ""
            ./monitor.sh ${{ github.event.inputs.duration }}

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rooted-playstore-logs-${{ github.run_number }}
          path: |
            frpc.log
            frpc.toml
          retention-days: 7
