name: High-End AVD with FRP KCP Tunnel

on:
  workflow_dispatch:
    inputs:
      duration:
        description: 'Session duration in hours (max 6)'
        required: false
        default: '4'
      api_level:
        description: 'Android API level'
        required: false
        default: '34'
        type: choice
        options:
          - '34'
          - '33'
          - '31'

jobs:
  run-emulator:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Enable KVM Hardware Acceleration
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install FRP Client v0.58.1
        run: |
          wget -q https://github.com/fatedier/frp/releases/download/v0.58.1/frp_0.58.1_linux_amd64.tar.gz
          tar -xzf frp_0.58.1_linux_amd64.tar.gz
          sudo cp frp_0.58.1_linux_amd64/frpc /usr/local/bin/
          sudo chmod +x /usr/local/bin/frpc

      - name: Create FRP Client Configuration with KCP
        run: |
          cat > frpc.toml << 'EOF'
          serverAddr = "159.195.6.61"
          serverPort = 7000
          
          # Enable KCP protocol for 30-40% latency reduction
          transport.protocol = "kcp"
          
          [[proxies]]
          name = "github-avd-adb"
          type = "tcp"
          localIP = "127.0.0.1"
          localPort = 5555
          remotePort = 5555
          
          [[proxies]]
          name = "github-avd-console"
          type = "tcp"
          localIP = "127.0.0.1"
          localPort = 5554
          remotePort = 5554
          EOF

      - name: Free Up Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost

      - name: AVD Cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ github.event.inputs.api_level }}-pixel6pro-v7

      - name: Create AVD Snapshot
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ github.event.inputs.api_level }}
          target: google_apis
          arch: x86_64
          profile: pixel_6_pro
          ram-size: 4096M
          heap-size: 512M
          disk-size: 8192M
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -camera-front none
          disable-animations: true
          script: echo "AVD snapshot created"

      - name: Start FRP KCP Tunnel
        run: |
          echo "🚀 Starting FRP with KCP protocol..."
          nohup frpc -c frpc.toml > frpc.log 2>&1 &
          sleep 5
          if pgrep -x "frpc" > /dev/null; then
            echo "✅ FRP KCP tunnel started successfully"
            echo "📊 Protocol: KCP (UDP-based, low latency)"
          else
            echo "❌ FRP failed to start"
            cat frpc.log
            exit 1
          fi

      - name: Create Monitoring Script
        run: |
          cat > monitor.sh << 'SCRIPT'
          #!/bin/bash
          DURATION_HOURS=$1
          DURATION_SECONDS=$((3600 * DURATION_HOURS))
          START_TIME=$(date +%s)
          
          echo "⏱️  Session: ${DURATION_HOURS} hours"
          echo "🕐 Started: $(date)"
          echo "🔥 Protocol: KCP (30-40% lower latency)"
          echo "✅ Emulator ready! Connect now from your device"
          echo ""
          
          ITERATION=0
          while true; do
            CURRENT_TIME=$(date +%s)
            ELAPSED=$((CURRENT_TIME - START_TIME))
            
            if [ $ELAPSED -ge $DURATION_SECONDS ]; then
              echo ""
              echo "✅ Session completed after ${DURATION_HOURS} hours"
              break
            fi
            
            REMAINING=$((DURATION_SECONDS - ELAPSED))
            HOURS=$((REMAINING / 3600))
            MINUTES=$(((REMAINING % 3600) / 60))
            
            ITERATION=$((ITERATION + 1))
            if [ $((ITERATION % 60)) -eq 0 ]; then
              DEVICES=$(adb devices | grep -c "5555.*device" || echo "0")
              FRP_STATUS="✅"
              pgrep -x "frpc" > /dev/null || FRP_STATUS="❌"
              echo "[$(date '+%H:%M:%S')] ⏳ ${HOURS}h ${MINUTES}m | 📱 ADB: ${DEVICES} | 🔗 KCP: ${FRP_STATUS}"
            fi
            
            sleep 1
          done
          
          echo "Session ended: $(date)"
          SCRIPT
          chmod +x monitor.sh

      - name: Start Emulator and Keep Session Alive
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ github.event.inputs.api_level }}
          target: google_apis
          arch: x86_64
          profile: pixel_6_pro
          ram-size: 4096M
          heap-size: 512M
          disk-size: 8192M
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -camera-front none -memory 4096 -cores 4 -skin 1080x2400
          disable-animations: true
          script: |
            echo "========================================="
            echo "   🚀 Android Emulator Started"
            echo "========================================="
            echo ""
            adb devices -l
            echo ""
            echo "⚙️  Enabling ADB over TCP/IP..."
            adb tcpip 5555
            sleep 5
            adb connect 127.0.0.1:5555
            sleep 2
            echo ""
            echo "========================================="
            echo "   📱 Device Information"
            echo "========================================="
            echo "Android Version: $(adb -s 127.0.0.1:5555 shell getprop ro.build.version.release)"
            echo "API Level: $(adb -s 127.0.0.1:5555 shell getprop ro.build.version.sdk)"
            echo "CPU: $(adb -s 127.0.0.1:5555 shell getprop ro.product.cpu.abi)"
            echo "Model: $(adb -s 127.0.0.1:5555 shell getprop ro.product.model)"
            echo ""
            echo "========================================="
            echo "   🌐 KCP TUNNEL READY (LOW LATENCY)"
            echo "========================================="
            echo ""
            echo "Connect from YOUR Android phone:"
            echo ""
            echo "  1. Open Bugjaeger or Termux"
            echo "  2. Connect: 159.195.6.61:5555"
            echo "  3. Protocol: KCP (automatic)"
            echo "  4. Latency: 30-40% lower than TCP"
            echo ""
            echo "  Or using ADB:"
            echo "  adb connect 159.195.6.61:5555"
            echo "  adb devices"
            echo "  adb shell"
            echo ""
            echo "========================================="
            echo "VPS IP: 159.195.6.61"
            echo "ADB Port: 5555"
            echo "Console Port: 5554"
            echo "Protocol: KCP (UDP)"
            echo "Expected Latency: ~30-40% lower"
            echo "========================================="
            echo ""
            ./monitor.sh ${{ github.event.inputs.duration }}

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: session-logs-kcp-${{ github.run_number }}
          path: |
            frpc.log
            frpc.toml
          retention-days: 7
